Blog/urls.py
from django.conf.urls import url

from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'(?P<id>\d+)/post_comment', views.post_comment, name='post_comment'),
    url(r'(?P<id>\d+)/$', views.blog_index, name='blog'),
]

WebSystem/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

admin.site.site_header = settings.ADMIN_SITE_HEADER
admin.site.site_title = settings.ADMIN_SITE_TITLE
admin.site.logout_template = 'admin/logout.html'

urlpatterns = [
    url(r'^', include('Blog.urls', namespace='Blog')),
    url(r'^blog/', include('Blog.urls', namespace='Blog')),
    url(r'^cnn/', include('cnn.urls', namespace='cnn')),
    url(r'^admin/', admin.site.urls),
]

cnn/urls.py
from django.conf.urls import url

from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'getImage', views.getImage, name='getImage'),
]

Blog/models.py
from django.db import models
from django.contrib import admin


# class Users(models.Model):
#     id = models.CharField(primary_key=True, unique=True, max_length=255)
#     email = models.CharField(unique=True, max_length=255)
#     password = models.CharField(max_length=255)
#     created_at = models.DateTimeField(auto_now_add=True)


class Blog(models.Model):
    id = models.AutoField(primary_key=True, unique=True)
    # user = models.ForeignKey(Users)
    title = models.CharField(max_length=255)
    text = models.TextField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)


class Comment(models.Model):
    id = models.AutoField(primary_key=True, unique=True)
    blog = models.ForeignKey(Blog)
    body = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

cnn/models.py
from django.db import models

# Create your models here.

Blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import *
from django.core import serializers
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
# Create your views here.


def index(request):
    blog = Blog.objects.order_by("-id")
    return render(request, 'index.html', {'blog': blog})


def blog_index(request, id):
    blog = Blog.objects.get(id=id)
    comments = Comment.objects.filter(blog_id=id)
    return render(request, 'blog.html', {'blog': blog, 'comments':comments})


def post_comment(request, id):
    comment = request.POST['comment']
    c = Comment(body=comment, blog_id=id)
    c.save()
    return redirect("/blog/"+id)

cnn/views.py
from django.shortcuts import render
from .models import *
import re
import base64
import cv2
import cnn.deeplearning as dl
import numpy as np
# Create your views here.


def index(request):
    return render(request, 'cnn.html')


def getImage(request):
    datauri = request.POST['img']
    img_str = re.search(r'base64,(.*)', datauri).group(1)
    nparr = np.fromstring(base64.b64decode(img_str), np.uint8)
    img_src = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
    img_negaposi = 255 - img_src
    img_gray = cv2.cvtColor(img_negaposi, cv2.COLOR_BGR2GRAY)
    thresh = 100
    max_pixel = 255
    ret, img_dst = cv2.threshold(img_gray,
                                 thresh,
                                 max_pixel,
                                 cv2.THRESH_BINARY)
    img_resize = cv2.resize(img_dst,(28,28))
    answer = dl.identification(img_resize)
    return render(request, 'cnn.html', {'answer':answer})

templates/answer.html
{% extends "base.html" %}

{% block extrahead %}
    <style>
        table {
            margin-top: 10px;
        }
    </style>
{% endblock %}

{% block body %}
    <div align="center">
        <h2>{{ answer }}</h2>
    </div>
{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"ja-jp" }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=devide-width,init-scale=1,user-scalable=no,minimum-scale=1,maximum-scale=1">
    <title>{% block title %}最終課題{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <style>
        h3 {
            padding: 0.7em 0 0.3em 1em;
        }
    </style>
    {#<link rel="shortcut icon" href="{{ STATICFILES_DIRS }}/static/favicon.ico" type="image/png">#}
    {% block extrahead %}{% endblock %}
</head>
<body onload="mam_draw_init();check();" align="center">
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">最終課題</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'Blog:index' %}">Blog</a></li>
                <li><a href="{% url 'cnn:index' %}">おまけ</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/admin">ログイン</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

<div class="container">
    {% block body %}
        {{ body }}
    {% endblock %}
</div>
</body>
</html>


<script>
    var can;
    var ct;
    var ox = 0, oy = 0, x = 0, y = 0;
    var mf = false;
    function mam_draw_init() {
        //初期設定
        can = document.getElementById("can");
        can.addEventListener("touchstart", onDown, false);
        can.addEventListener("touchmove", onMove, false);
        can.addEventListener("touchend", onUp, false);
        can.addEventListener("mousedown", onMouseDown, false);
        can.addEventListener("mousemove", onMouseMove, false);
        can.addEventListener("mouseup", onMouseUp, false);
        ct = can.getContext("2d");
        ct.strokeStyle = "#000000";
        ct.lineWidth = 20;
        ct.lineJoin = "round";
        ct.lineCap = "round";
        clearCan();
    }
    function onDown(event) {
        mf = true;
        ox = event.touches[0].pageX - event.target.getBoundingClientRect().left;
        oy = event.touches[0].pageY - event.target.getBoundingClientRect().top;
        event.stopPropagation();
    }
    function onMove(event) {
        if (mf) {
            x = event.touches[0].pageX - event.target.getBoundingClientRect().left;
            y = event.touches[0].pageY - event.target.getBoundingClientRect().top;
            drawLine();
            ox = x;
            oy = y;
            event.preventDefault();
            event.stopPropagation();
        }
    }
    function onUp(event) {
        mf = false;
        event.stopPropagation();
    }

    function onMouseDown(event) {
        ox = event.clientX - event.target.getBoundingClientRect().left;
        oy = event.clientY - event.target.getBoundingClientRect().top;
        mf = true;
    }
    function onMouseMove(event) {
        if (mf) {
            x = event.clientX - event.target.getBoundingClientRect().left;
            y = event.clientY - event.target.getBoundingClientRect().top;
            drawLine();
            ox = x;
            oy = y;
        }
    }
    function onMouseUp(event) {
        mf = false;
    }
    function drawLine() {
        ct.beginPath();
        ct.moveTo(ox, oy);
        ct.lineTo(x, y);
        ct.stroke();
    }
    function clearCan() {
        ct.fillStyle = "rgb(255,255,255)";
        ct.fillRect(0, 0, can.getBoundingClientRect().width, can.getBoundingClientRect().height);
    }
</script>

<script>
    function check(){
        var strName;
        strName = document.getElementById("test").textContent;
        strName = strName.replace("/[\n\r]/g", "<br>");
        test.innerHTML = strName;
        document.body.onload=check;
    }
</script>

templates/blog.html
{% extends "base.html" %}

{% block extrahead %}
<style>
    table {
      margin-top: 10px;
    }
    a:link { color: #000000; }
    a:visited { color: #000000; }
    a:hover { color: #000000; }
    a:active { color: #000000; }
</style>
{% endblock %}

{% block body %}
    <div class="container">
    <br>
        <h1 class="page-header">{{ blog.title }}</h1>
        <h4>{{ blog.text|linebreaksbr }}</h4>
        <br /><br />
    </div>

    <button data-toggle="collapse" data-target="#demo" class="btn btn-primary btn-md">コメント欄</button>
    <div id="demo" class="collapse" align="center">
        <ul class="list-group" style="width: 500px;">
        <br>
            {% for comment in comments %}
                <li class="list-group-item">{{ comment.body }} [{{ comment.created_at }}]</li>
            {% endfor %}
         </ul>
    </div>

    <br /><br />

    <form action="/blog/{{ blog.id }}/post_comment" method="post">
        <div class="form-group" align="center">
            <label for="comment">コメント:</label>
            <input type='text' class="form-control" id="comment" name="comment" style="width: 300px;">
        </div>
        <button type="submit" class="btn btn-success btn-md">投稿</button>
    </form>

{% endblock %}

templates/cnn.html
{% extends "base.html" %}

{% block extrahead %}
    <style>
        table {
            margin-top: 10px;
        }
    </style>
    <script>
        function saveImg() {
            var img = document.getElementById("can").toDataURL('image/png');
            console.log(img);
            img = img.replace('image/png', 'image/octet-stream');
            document.getElementById("img").value = img;
        }
    </script>
{% endblock %}

{% block body %}
    <div align="center">
    <br>

    <h1 class="page-header">手書き文字認識(0~9)</h1>
    <div style="border:solid 1px #000000;width:282px;height:282px" id="candiv">
        <canvas id="can" width="280px" height="280px"></canvas>
    </div>
    <form action="/cnn/getImage" method="post">
        <button type="button" onClick="clearCan();" value="クリア" style="width:100;height:30;" data-inline="true" class="btn btn-danger btn-md">クリア</button>
        <button type="submit" id="img" name="img" onclick="saveImg()" value="認識" style="width:100;height:30;" data-inline="true" class="btn btn-success btn-md">認識</button>
    </form>
    <h1>{% if answer != None %}答えは<span style="color:red;font-size:7ex;">{{ answer }}</span>だ！！！{% endif %}</h1>
    </div>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block extrahead %}
<style>
    table {
      margin-top: 10px;
    }
    a:link { color: #000000; }
    a:visited { color: #000000; }
    a:hover { color: #000000; }
    a:active { color: #000000; }
</style>
{% endblock %}

{% block body %}
    <br>
    <h1 class="page-header">Blog</h1>
    <div align="center">
        <div class="list-group" style="width: 400px;">
             {% for blog in blog.all %}
                 <a href="blog/{{ blog.id}}" class="list-group-item" style="width: 400px;">{{ blog.title }} : [{{ blog.created_at}}]</a>
             {% endfor %}
        </div>
    </div>
{% endblock %}